version: '3.8'

services:
  # Central Authority Service
  ca:
    build: ./ca
    ports:
      - "9000:9000"
    volumes:
      - ./ca:/app/ca
      - ca-certs:/app/certs
    environment:
      - PYTHONPATH=/app
      - CA_PORT=9000
    networks:
      - fl-network
    command: python ca_service.py

  # Enhanced Dashboard with Research Demo
  dashboard:
    build: ./dashboard
    ports:
      - "5000:5000"
    volumes:
      - ./Datapre:/app/data:ro
      - ./server:/app/server:ro
      - ./clients:/app/clients:ro
      - ./ca:/app/ca:ro
      - ./attack_detection_service.py:/app/attack_detection_service.py:ro
      - ./demo_presentation.py:/app/demo_presentation.py:ro
      - ./start_research_demo.py:/app/start_research_demo.py:ro
      - ./presentation_guide.md:/app/presentation_guide.md:ro
      - ./RESEARCH_PROJECT_SUMMARY.md:/app/RESEARCH_PROJECT_SUMMARY.md:ro
      - dashboard-logs:/app/logs
      - demo-results:/app/demo_results
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - DASHBOARD_PORT=5000
      - CA_URL=http://ca:9000
    networks:
      - fl-network
    depends_on:
      - ca
      - server
    restart: unless-stopped

  # Enhanced Server
  server:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - ./Datapre:/app/data:ro
      - ./global_model.pkl:/app/global_model.pkl
      - server-logs:/app/logs
      - ca-certs:/app/certs:ro
    environment:
      - PYTHONPATH=/app
      - SERVER_PORT=8080
      - MIN_CLIENTS=10
      - NUM_ROUNDS=10
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    networks:
      - fl-network
    command: python server.py
    restart: unless-stopped

  # Client Services (Dynamic scaling)
  client1:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client1:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8082:8082"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=1
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 1
    restart: unless-stopped

  client2:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client2:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8083:8083"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=2
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 2
    restart: unless-stopped

  client3:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client3:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8084:8084"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=3
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 3
    restart: unless-stopped

  client4:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client4:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8085:8085"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=4
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 4
    restart: unless-stopped

  client5:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client5:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8086:8086"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=5
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 5
    restart: unless-stopped

  client6:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client6:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8087:8087"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=6
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 6
    restart: unless-stopped

  client7:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client7:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8088:8088"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=7
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 7
    restart: unless-stopped

  client8:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client8:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8089:8089"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=8
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 8
    restart: unless-stopped

  client9:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client9:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8090:8090"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=9
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 9
    restart: unless-stopped

  client10:
    build: ./clients
    volumes:
      - ./Datapre:/app/data:ro
      - ./clients/client10:/app/client:ro
      - ca-certs:/app/certs:ro
      - client-logs:/app/logs
    working_dir: /app/client
    ports:
      - "8091:8091"  # Demo control port
    environment:
      - PYTHONPATH=/app
      - CLIENT_ID=10
      - SERVER_ADDRESS=server:8080
      - CA_URL=http://ca:9000
      - ENABLE_CERTIFICATES=true
    depends_on:
      - server
      - ca
    networks:
      - fl-network
    command: python client.py 10
    restart: unless-stopped

  # Monitoring and Logging
  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - fl-network
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    # ports:
    #   - "3002:3000"
    volumes:
      - grafana-data:/var/lib/grafana
      - ./monitoring/grafana/provisioning:/etc/grafana/provisioning
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - fl-network
    depends_on:
      - prometheus
    restart: unless-stopped

  # Redis for caching and session management
  redis:
    image: redis:alpine
    volumes:
      - redis-data:/data
    networks:
      - fl-network
    restart: unless-stopped

  # Research Demo Service
  research-demo:
    build: ./dashboard
    ports:
      - "5001:5000"
    volumes:
      - ./demo_presentation.py:/app/demo_presentation.py:ro
      - ./start_research_demo.py:/app/start_research_demo.py:ro
      - ./presentation_guide.md:/app/presentation_guide.md:ro
      - ./RESEARCH_PROJECT_SUMMARY.md:/app/RESEARCH_PROJECT_SUMMARY.md:ro
      - demo-results:/app/demo_results
      - research-logs:/app/logs
    environment:
      - PYTHONPATH=/app
      - FLASK_ENV=production
      - DASHBOARD_PORT=5000
    networks:
      - fl-network
    command: python demo_presentation.py
    restart: unless-stopped

  # Nginx reverse proxy
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - nginx-logs:/var/log/nginx
    depends_on:
      - dashboard
      - server
    networks:
      - fl-network
    restart: unless-stopped

volumes:
  ca-certs:
    driver: local
  dashboard-logs:
    driver: local
  server-logs:
    driver: local
  client-logs:
    driver: local
  prometheus-data:
    driver: local
  grafana-data:
    driver: local
  redis-data:
    driver: local
  nginx-logs:
    driver: local
  demo-results:
    driver: local
  research-logs:
    driver: local

networks:
  fl-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
